### ISSUE TITLE
Problem with colors library

### ISSUE THREAD

**Issue by dillam** [GatorGauge/GatorGauge#109]
I used the instructions in the readme to install the dependencies. When I run the program I get the following error
```
Traceback (most recent call last):
  File "gator_gauge.py", line 9, in <module>
    import display
  File "/home/d/dillam/cs280f2017/cs280f2017-dillam/labs/GatorGauge/display.py", line 6, in <module>
    from colors import bold
ImportError: No module named 'colors'
```

**Comment by toccinAC** [comment]
You have to pip3 install colors. That should fix it. It should be added to the requirements.

**Comment by toccinAC** [comment]
I mean colorama not colors.

**Comment by dillam** [comment]
This issue was solved by using the command
```bash
pip3 install ansicolors
```
