### ISSUE TITLE
Analyze commits not working

### ISSUE THREAD

**Issue by dillam** [GatorGauge/GatorGauge#114]
When I run the `analyze commits` command, I get the following error.

```
Welcome to GatorGauge!
Type help to see list of commands.
>>> analyze commits
Traceback (most recent call last):
  File "gator_gauge.py", line 107, in <module>
    analyze_commits.analyze_commits(OUT)
  File "/Users/TheTrainstation/Allegheny/cs280/GatorGauge/analyze_commits.py", line 12, in analyze_commits
    return_list = get_list_of_commits(out)
  File "/Users/TheTrainstation/Allegheny/cs280/GatorGauge/parse_commits.py", line 44, in get_list_of_commits
    return get_list_of_each_commit(get_commits_for_all_repos(out))
  File "/Users/TheTrainstation/Allegheny/cs280/GatorGauge/parse_commits.py", line 17, in get_commits_for_all_repos
    repository = Repo(repo)
  File "/Users/TheTrainstation/Library/Python/3.5/lib/python/site-packages/dulwich/repo.py", line 696, in __init__
    "No git repository was found at %(path)s" % dict(path=root)
dulwich.errors.NotGitRepository: No git repository was found at computer-science-111-fall-2017-lab-1-altmeyera

```

**Comment by burrowss** [comment]
I'm encountering the same error. I'll try to look into it. maybe @lylet-AC can help

**Comment by mariakimheinert** [comment]
@ZachAndrews98 didn't we solve this issue in lab last week? Is it possible that the fix wasn't merged?

**Comment by ZachAndrews98** [comment]
A fix for the above error has been merged into master, however, a different error may now exist according to @burrowss.

**Comment by burrowss** [comment]
@ZachAndrews98 So it looks like it was only my laptop that was not working due to dulwich not being installed correctly since I was able to run it just fine using X2Go. So I think we should be all good
